"""Offline demo on a synthetic cohort.

The cohort is generated by simple arithmetic (no randomness, no real data):
participant IDs SYN0000..., ages 16-90, two sex codes, three APOE-style
genotype labels with the e4/e4 group deliberately small, and a few withdrawn.

Run from the repository root:  python examples/demo.py
"""

from __future__ import annotations

import json

from recall_gen import EligibilityFilter, ProtocolGenerator, StudyDesigner
from recall_gen.designer import ParticipantRecord


def synthetic_cohort(n: int = 600) -> list[ParticipantRecord]:
    people = []
    for i in range(n):
        if i % 40 == 0:
            group = "e4/e4"
        elif i % 4 == 0:
            group = "e3/e4"
        else:
            group = "e3/e3"
        people.append(
            ParticipantRecord(
                participant_id=f"SYN{i:04d}",
                genotype_group=group,
                age=16 + (i * 37) % 75,
                sex="F" if i % 3 else "M",
                consent_status="withdrawn" if i % 29 == 0 else "active",
            )
        )
    return people


def main() -> None:
    cohort = synthetic_cohort()

    eligibility = (
        EligibilityFilter()
        .add_stage("withdrawn", lambda p: p.consent_status != "active")
        .add_stage("under_18", lambda p: p.age < 18)
        .add_stage("over_80", lambda p: p.age > 80)
    )
    result = eligibility.apply(cohort)
    print(f"Cohort: {result.total_input}; eligible: {result.total_eligible}")
    for stage, count in result.excluded_per_stage.items():
        print(f"  excluded at {stage}: {count}")

    design = StudyDesigner(target_per_group=20).design(result.eligible, "Synthetic APOE recall")
    print()
    for group in sorted(design.groups):
        lo, hi = design.age_range[group]
        sexes = ", ".join(f"{s}={n}" for s, n in sorted(design.balance_summary[group].items()))
        short = design.shortfall.get(group, 0)
        note = f"  (short by {short})" if short else ""
        print(f"{group}: {design.group_sizes[group]} selected; {sexes}; ages {lo}-{hi}{note}")

    protocol = ProtocolGenerator().generate(design)
    print()
    print(json.dumps({"study_name": protocol.study_name, "groups": design.group_sizes}))


if __name__ == "__main__":
    main()
